---
driver:
  name: vagrant

provisioner:
  hosts: repo-server
  name: ansible_playbook
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbosity: 2
  ansible_verbose: true


platforms:
  - name: bento/centos-6.7

suites:
  - name: repo-server
    driver:
      memory: 1024
      vm_hostname: repo
      server_name: repo
      network:
      - [ 'forwarded_port', {guest: 80, host: 8000} ]
      - [ 'private_network', { ip: '192.168.1.150' } ]
    provisioner:
      playbook: tests/test.yml


# Fix for: https://github.com/neillturner/kitchen-ansible/issues/66
verifier:
  ruby_bindir: '/usr/bin'